config/routes.rb
Rails.application.routes.draw do
  # get 'charges/new'
  # get 'charges/create'
  resources :orders do
    get :my_orders, on: :collection
  end
  resources :vehicles do
    get :my_vehicles, on: :collection
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }


  resources :charges, only: [:new, :create]
      #  devise_for :users
       resources :posts
      #  root to: 'posts#index'



  get "/details/:id", to: "vehicles#confirm_order"
  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :vehicle
  belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
    end
    def create
        user = current_user
       @order = user.orders.new(vehicle_id: params[:vehicle_id])
       @order.save
       flash[:notice] ="order created successfully!"
       redirect_to vehicles_path
    end

    def my_orders
        # debugger
        @orders = Order.where(user_id: current_user.id)
    end

    def destroy
        @order = Order.find(params[:id])
        @order.destroy
        redirect_to my_orders_orders_path
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<h1>this is index</h1>

app/views/orders/my_orders.html.erb
<span><h1 class="text-dark text-center ">My Orders</h1></span>
 <div class="container">
  <div class="row">
<% @orders.each do |order| %>
       <div class="card col-2 mx-2 my-2">
      <h4 class="text-primary"> Order </h4>
      <p><strong>Oreder Id:</strong>
         <%= order.id %></p>
         <p><strong>Vehicle Model:</strong>
         <%=order.vehicle.model %></p>
         <p><strong>Payment Status:</strong>
         <span style="color:red;"><%=order.status%></span></p>
         <div class="row mb-2">
            <div class="col-6">
              <%= button_to "Delete", order, method: :delete, class:" text-danger"%>
            </div>
            <div class="col-6">
              <%= link_to "Pay", new_charge_path, style:"color:orange; text-decoration: none;"%>
            </div>
         </div>
         
     
      </div>
   <% end %>
   </div>
 </div>