config/routes.rb
Rails.application.routes.draw do
  # get 'charges/new'
  # get 'charges/create'
  resources :orders do
    get :my_orders, on: :collection
  end
  resources :vehicles do
    get :my_vehicles, on: :collection
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }


  resources :charges, only: [:new, :create]
      #  devise_for :users
       resources :posts
      #  root to: 'posts#index'



  get "/details/:id", to: "vehicles#confirm_order"
  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    belongs_to :owner, class_name: "User"
    has_one_attached :image , dependent: :destroy
    has_many :orders
end

app/controllers/vehicles_controller.rb
class VehiclesController < InheritedResources::Base

  def index
    @vehicles = Vehicle.all
  end

  def create
    @vehicle = current_user.vehicles.new(vehicle_params)
    if @vehicle.save 
      redirect_to my_vehicles_vehicles_path
    else
      render "new"
    end
  end

  def Show
    @vehicle = Vehicle.find(params[:id])
  end
   
  def my_vehicles
    #debugger
    @vehicles = Vehicle.where(owner_id: current_user.id)
    # render 'index'
  end
  def destroy
    @vehicle = Vehicle.find(params[:id])
    # debugger
    @vehicle.destroy
    redirect_to  my_vehicles_vehicles_path

  end

  def confirm_order
    @vehicle = Vehicle.find(params[:id])
  end
  private

    def vehicle_params
      params.require(:vehicle).permit(:model, :color, :fuel_type, :price, :image)
    end


end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<div class="container">
<%= form_with(model: vehicle) do |form| %>
  <% if vehicle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-25">
    <%= form.label :Model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div class="w-25 mt-1">
    <%= form.label :Color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div class="w-25 mt-1">
    <%= form.label :Fuel_type, style: "display: block" %>
    <%= form.text_field :fuel_type %>
  </div>

  <div class="w-25 mt-1">
    <%= form.label :Price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  

  <div class="w-25 mt-1">
    <%= form.label :Image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div class="w-25 mt-4">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/vehicles/_vehicle.html.erb
<div >
<% if vehicle.image.attached? %>
<div>
<%= image_tag vehicle.image, style: "width: 100%"%>
</div>
<% end %>
     
       <strong>Model:</strong>
       <%= vehicle.model %>
       <br>
       <strong>Color:</strong>
       <%= vehicle.color %>
       <br>
       <strong>Fuel type:</strong>
       <%= vehicle.fuel_type %>
       <br>
       <strong>Price:</strong>
       <%= vehicle.price %>
    
     
   
</div>

app/views/vehicles/confirm_order.html.erb
<div>
<strong>Model:</strong>
       <%= @vehicle.model %>
       <br>
       <strong>Color:</strong>
       <%= @vehicle.color %>
       <br>
       <strong>Fuel type:</strong>
       <%= @vehicle.fuel_type %>
       <br>
       <strong>Price:</strong>
       <%= @vehicle.price %>
<%= button_to "Proceed", orders_path(vehicle_id: @vehicle.id), method: :post %>
</div>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

app/views/vehicles/index.html.erb
<p style="color: green"><%= notice %></p>

<span><h1 class="text-dark text-center ">Vehicles</h1></span>

<div id="vehicles" class="container">
   <div class="row ">
     <% @vehicles.each do |vehicle| %>
       <% if vehicle.owner_id != current_user.id%>
        <div class="card col-2 bg-success mx-2 my-2">
          <div >
            <% if vehicle.image.attached? %>
              <div>
                <%= image_tag vehicle.image, style: "width: 100%; height: 150px"%>
              </div>
            <% end %>
      
            <strong>Model:</strong>
            <%= vehicle.model %>
            <br>
            <strong>Color:</strong>
            <%= vehicle.color %>
            <br>
            <strong>Fuel type:</strong>
            <%= vehicle.fuel_type %>
            <br>
            <strong>Price:</strong>
            <%= vehicle.price %>
          </div>

          <hr>
          <div class="row">
            <div class="col-6">
              <%= link_to "details", vehicle, class:"text-dark", style:"text-decoration:none"%>
            </div>
            <div class="col-6">
              <%= link_to "Buy Now", "/details/#{vehicle.id}" ,  class:"text-decoration-none text-danger"%>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
   <%= link_to 'Back', :back %>

</div>

app/views/vehicles/my_vehicles.html.erb
<span><h1 class="text-dark text-center ">My Vehicles</h1></span>

<div id="vehicles" class="container">
   <div class="row ">
      <% @vehicles.each do |vehicle| %>
     
     <div class="card col-3 bg-success mx-3 my-3">

      <div>
         <% if vehicle.image.attached? %>
         <div class="mt-2">
         <%= image_tag vehicle.image, style: "width: 100%; height: 200px"%>
         </div>
         <% end %>
     
         <strong>Model:</strong>
         <%= vehicle.model %>
         <br>
         <strong>Color:</strong>
         <%= vehicle.color %>
         <br>
         <strong>Fuel type:</strong>
         <%= vehicle.fuel_type %>
         <br>
         <strong>Price:</strong>
         <%= vehicle.price %> 
      </div>
      <hr>
      <div style="display: inline-flex; padding-bottom:8px;">
       
         <%= link_to "Show", vehicle, class:"text-white text-decoration-none" %> &nbsp;|&nbsp;
       

         <%= link_to "Edit", edit_vehicle_path(vehicle), class:"text-decoration-none text-white"%> &nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
       
         <%= button_to "Delete", vehicle, method: :delete, class:" text-danger " %>
      </div>
    
     </div>
    <% end %>

   </div>

</div>

app/views/vehicles/new.html.erb
<div class="container">
<h1 class="text-dark">Add your car details</h1>

<%= render "form", vehicle: @vehicle %>

<br>

</div>

app/views/vehicles/show.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>
 
<div>
<%= render @vehicle %>
<div>

</div>