config/routes.rb
Rails.application.routes.draw do
  # get 'charges/new'
  # get 'charges/create'
  resources :orders do
    get :my_orders, on: :collection
  end
  resources :vehicles do
    get :my_vehicles, on: :collection
  end
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }


  resources :charges, only: [:new, :create]
      #  devise_for :users
       resources :posts
      #  root to: 'posts#index'



  get "/details/:id", to: "vehicles#confirm_order"
  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :vehicle
  belongs_to :user
end

app/models/user.rb
class User <  ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vehicles, foreign_key: "owner_id"
  has_many :orders
  has_one_attached :image , dependent: :destroy

  after_create :welcome_email
  def welcome_email
    UserMailer.welcome_email(self).deliver
    # redirect_to root_path, alert: "Thank you for registration."
  end
  # validates :email, uniqueness: true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    belongs_to :owner, class_name: "User"
    has_one_attached :image , dependent: :destroy
    has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    respond_to :html, :json
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    
    # def after_sign_up_path_for(resource)
    #     'home/index' # Or :prefix_to_your_route
    # end

    def after_sign_in_path_for(resource)
        '/vehicles' # Or :prefix_to_your_route
    end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :address, :contact_no, :email, :password, :password_confirmation])
  end

end


# devise_parameter_sanitizer.for(:sign_up) { |u| params.require(u)(:firstname, :designation_id, :middlename, :previous_experiance_year, :previous_experiance_month, :lastname, :email, :username, :password, :password_confirmation, :previous_experiance, :empid, :dob, :timezone, :doj, :gender, :education, :comments, :locked, :deactivated, :reason, :phone, :deactivated_date, :image) }

# params.require(:user)

app/controllers/charges_controller.rb
# class ChargesController < ApplicationController
#   def new
#     # debugger
#   end

#   def create

#     @amount = 500

#   customer = Stripe::Customer.create(
#     email: params[:stripeEmail],
#     source: params[:stripeToken]
#   )

#   charge = Stripe::Charge.create(
#     customer: customer.id,
#     amount: @amount,
#     description: 'Rails Stripe customer',
#     currency: 'usd'
#   )

#   rescue Stripe::CardError => e
#   flash[:error] = e.message
#   redirect_to new_charge_path
#   end
# end
class ChargesController < ApplicationController
  # rescue_from Stripe::CardError, with: :catch_exception
  # def new
  # end

  # def create
  #   StripeChargesServices.new(charges_params, current_user).call
  #   redirect_to new_charge_path
  # end

  # private

  def charges_params
    params.permit(:stripeEmail, :stripeToken, :order_id)
  end

  def catch_exception(exception)
    flash[:error] = exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
    end
    def create
        user = current_user
       @order = user.orders.new(vehicle_id: params[:vehicle_id])
       @order.save
       flash[:notice] ="order created successfully!"
       redirect_to vehicles_path
    end

    def my_orders
        # debugger
        @orders = Order.where(user_id: current_user.id)
    end

    def destroy
        @order = Order.find(params[:id])
        @order.destroy
        redirect_to my_orders_orders_path
    end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/vehicles_controller.rb
class VehiclesController < InheritedResources::Base

  def index
    @vehicles = Vehicle.all
  end

  def create
    @vehicle = current_user.vehicles.new(vehicle_params)
    if @vehicle.save 
      redirect_to my_vehicles_vehicles_path
    else
      render "new"
    end
  end

  def Show
    @vehicle = Vehicle.find(params[:id])
  end
   
  def my_vehicles
    #debugger
    @vehicles = Vehicle.where(owner_id: current_user.id)
    # render 'index'
  end
  def destroy
    @vehicle = Vehicle.find(params[:id])
    # debugger
    @vehicle.destroy
    redirect_to  my_vehicles_vehicles_path

  end

  def confirm_order
    @vehicle = Vehicle.find(params[:id])
  end
  private

    def vehicle_params
      params.require(:vehicle).permit(:model, :color, :fuel_type, :price, :image)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carbooking</title>
    <link rel="icon" type="image/x-icon" href="https://cardefender.ca/wp-content/uploads/2019/01/cropped-favicon-300x300.png">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <header class="bg-white fixed-top">
  <div class="containern">

   <div class="row">
   <div class="col-8">
  <ul class="nav" style="padding: 2px,3px,3px,2px">

  <li class="nav-item">
  <img src="https://t4.ftcdn.net/jpg/00/76/00/65/360_F_76006563_NEh2uRX5XSYHbHtJB0vvcGzrWvUdpIx2.jpg" alt="image" class="w-25">
  </li>

  <li class="nav-item mt-3">
    <%= link_to "Home", root_path, class:"nav-link text-dark ", style:"text-decoration:none;" %>
  </li>
  <% if current_user %>
  <li class="nav-item mt-3">
    <%= link_to "Vehicles", vehicles_path, class:"nav-link text-dark", style:"text-decoration:none;"%>
  </li>
  <% end %>

  <% if !current_user %>

  <li class="nav-item mt-3">
  <%= link_to "sign in", new_user_session_path , class:"nav-link text-dark", style:"text-decoration:none;"%>
  </li>

  <li class="nav-item mt-3">
  <%= link_to "sign up", new_user_registration_path , class:"nav-link text-dark", style:"text-decoration:none;"%>
  </li>

   <%else%>
  <li class="nav-item mt-3">
  <%= link_to "My vehicles", my_vehicles_vehicles_path, class:"nav-link text-dark", style:"text-decoration:none;" %>
  </li>

  <li class="nav-item mt-3">
  <%= link_to "Sell car", new_vehicle_path, class:"nav-link text-dark ", style:"text-decoration:none;"%>
  </li>

  <li class="nav-item mt-3">
  <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link text-dark text-decoration-none" %>
  </li>

  <li class="nav-item mt-3">
  <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-dark" %>
  </li>
  
  <%end%>

  
</ul>
</div>
 <div class="col-4 mt-3">
 <% if current_user %>
   <%= link_to "my orders", my_orders_orders_path, class:"text-info btn btn-dark text-decoration-none" %>
 <%end%>

 </div>
</div>
</div>
  </header>


  
  <body >  
    <div class="bg">
    <%= yield %>
    </div>
    
  </body>
  
  
  
</html>